### ISSUE TITLE
aws.elb.DeregisterInstance should take a wildcard for ELB name

### ISSUE THREAD

**Issue by diranged** [Nextdoor/kingpin#305]
I think that `aws.elb.DeregisterInstance` should allow you to pass in a `*` for the ELB name -- and if thats true, it'll find *all ELBs* where its registered and remove the instance from all of them. This is extremely useful in the case where your host is running many services and hooked up to many ELBs.

**Comment by siminm** [comment]
Assuming I understand your usecase correctly the easier approach here would
be to agree on a conventional healthcheck and fail that healthcheck while
the rest of the systems are working fine. This places the deregistration
responsibility on the EC2 instance instead of an unknown number of ELBs

On Wed, Dec 9, 2015 at 11:53 AM, Matt W <notifications@github.com> wrote:

> Assigned #305 <https://github.com/Nextdoor/kingpin/issues/305> to @siminm
> <https://github.com/siminm>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Nextdoor/kingpin/issues/305#event-487350393>.
>



-- 
Mikhail Simin, Ph.D
*Nextdoor* <http://nextdoor.com/>
The Private Social Network for Neighborhoods

**Comment by nextdoor-ops-ro** [comment]
Nah  -- that means you have some system-level healthcheck that has nothing
to do with the actual underlying application. Thats not what we would want
at all -- if a container or service stoppd, the healthcheck would keep
returning positive.

No, I'm talking about just giving a host the ability to say "gracefully get
me out of any ELB i'm registered in"...

Matt Wise
Sr. Systems Architect
Nextdoor.com
